<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// モデル
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->target_3();
        //$this->target_4();
    }

    public function target_3()
    {
        // 対象月=3月を反映する前時点の想定データ
        User::create([
            'user_id'                       => 'katahira',
            'employee_no'                   => '0134',
            'user_name'                     => '片平 貴順',
            'email'                         => 't.katahira@warm.co.jp',
            'password'                      => bcrypt('katahira134'),
            'is_active'                     => true,
            'role_id'                       => 'system_admin',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2017/09/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => 20,
            'granted_days'                  => 20,
            'used_days'                     => 18.5,
            'required_deadline'             => '2026/03/31',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 5,
            'used_days_reset_year_month'    => '202604',
            'grant_type'                    => 3,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => 'nozomi',
            'employee_no'                   => '0228',
            'user_name'                     => '片平 希望',
            'email'                         => 'n.katahira@warm.co.jp',
            'password'                      => bcrypt('katahira228'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/05/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => 10,
            'used_days'                     => 4,
            'required_deadline'             => '2026/10/31',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 2,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 1,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => 'yamamura',
            'employee_no'                   => '0234',
            'user_name'                     => '山村 祐一',
            'email'                         => 'y.yamamura@warm.co.jp',
            'password'                      => bcrypt('yamamura234'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/11/17',
            'next_grant_year_month'         => '202605',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => null,
            'used_days'                     => 0,
            'required_deadline'             => null,
            'carried_over_required_days'    => null,
            'granted_required_days'         => null,
            'used_days_reset_year_month'    => '202804',
            'grant_type'                    => 0,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => '2nd',
            'employee_no'                   => '0333',
            'user_name'                     => '2回目で週4から週5に変わる人',
            'email'                         => null,
            'password'                      => bcrypt('11111111'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/08/01',
            'next_grant_year_month'         => '202602',
            'work_days_per_week'            => '標準（週所定労働日数が４日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => 8,
            'used_days'                     => 2,
            'required_deadline'             => null,
            'carried_over_required_days'    => null,
            'granted_required_days'         => null,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 1,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => 'aaa',
            'employee_no'                   => '0334',
            'user_name'                     => '10月入社で1回目の人',
            'email'                         => null,
            'password'                      => bcrypt('11111111'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/10/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => null,
            'used_days'                     => null,
            'required_deadline'             => null,
            'carried_over_required_days'    => null,
            'granted_required_days'         => null,
            'used_days_reset_year_month'    => '202804',
            'grant_type'                    => 0,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => 'aaab',
            'employee_no'                   => '0335',
            'user_name'                     => '10月入社で2回目の人',
            'email'                         => null,
            'password'                      => bcrypt('11111111'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2024/10/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => 10,
            'used_days'                     => 5,
            'required_deadline'             => '2026/03/31',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 5,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 1,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => '2ndssss',
            'employee_no'                   => '0444',
            'user_name'                     => '2回目で週5から週2に変わる人',
            'email'                         => null,
            'password'                      => bcrypt('11111111'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2024/10/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => 10,
            'used_days'                     => 5,
            'required_deadline'             => '2026/03/31',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 5,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 1,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => '2ndssssaaa',
            'employee_no'                   => '0555',
            'user_name'                     => '9月入社)2回目で週5から週2に変わる人',
            'email'                         => null,
            'password'                      => bcrypt('11111111'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/09/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => 10,
            'used_days'                     => null,
            'required_deadline'             => '2027/02/28',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 5,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 1,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => '2ndssssaaaff',
            'employee_no'                   => '0666',
            'user_name'                     => '9月入社で1回目=義務有、2回目=義有',
            'email'                         => null,
            'password'                      => bcrypt('11111111'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/09/01',
            'next_grant_year_month'         => '202604',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => 10,
            'used_days'                     => 2,
            'required_deadline'             => '2027/02/28',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 5,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 1,
            'paid_leave_updated_at'         => null,
        ]);
    }

    public function target_4()
    {
        // 対象月=4月を反映する前時点の想定データ
        User::create([
            'user_id'                       => 'katahira',
            'employee_no'                   => '0134',
            'user_name'                     => '片平 貴順',
            'email'                         => 't.katahira@warm.co.jp',
            'password'                      => bcrypt('katahira134'),
            'is_active'                     => true,
            'role_id'                       => 'system_admin',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2017/09/01',
            'next_grant_year_month'         => '202704',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => 20,
            'granted_days'                  => 20,
            'used_days'                     => 0,
            'required_deadline'             => '2027/03/31',
            'carried_over_required_days'    => null,
            'granted_required_days'         => 5,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 3,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => 'nozomi',
            'employee_no'                   => '0228',
            'user_name'                     => '片平 希望',
            'email'                         => 'n.katahira@warm.co.jp',
            'password'                      => bcrypt('katahira228'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/05/01',
            'next_grant_year_month'         => '202704',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => 10,
            'granted_days'                  => 11,
            'used_days'                     => 7,
            'required_deadline'             => '2027/03/31',
            'carried_over_required_days'    => 7,
            'granted_required_days'         => null,
            'used_days_reset_year_month'    => '202704',
            'grant_type'                    => 2,
            'paid_leave_updated_at'         => null,
        ]);
        User::create([
            'user_id'                       => 'yamamura',
            'employee_no'                   => '0234',
            'user_name'                     => '山村 祐一',
            'email'                         => 'y.yamamura@warm.co.jp',
            'password'                      => bcrypt('yamamura234'),
            'is_active'                     => true,
            'role_id'                       => 'user',
            'base_id'                       => 'honsha',
            'is_password_change_required'   => false,
            'hire_date'                     => '2025/11/17',
            'next_grant_year_month'         => '202605',
            'work_days_per_week'            => '標準（週所定労働日数が５日等の社員用）',
            'carried_over_days'             => null,
            'granted_days'                  => null,
            'used_days'                     => 0,
            'required_deadline'             => null,
            'carried_over_required_days'    => null,
            'granted_required_days'         => null,
            'used_days_reset_year_month'    => '202804',
            'grant_type'                    => 0,
            'paid_leave_updated_at'         => null,
        ]);
    }
}